FROM debian:bullseye-slim

RUN apt-get update
RUN apt-get -y full-upgrade
RUN apt-get -y install build-essential vim autoconf texinfo zlib1g-dev libgccjit-10-dev libgnutls28-dev git pkg-config libncurses-dev libharfbuzz-dev libcairo2-dev libx11-dev libxaw7-dev libtiff-dev libgif-dev libjpeg-dev libjansson-dev libgpm-dev librsvg2-dev liblcms2-dev libxml2-dev xaw3dg-dev libotf-dev 

# using local cloned repo that will be mounted on docker run
WORKDIR /emacs-src
